# Generated by Django 5.2 on 2025-05-04 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="owner",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "student"},
                related_name="enrolled_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Студент",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="courses.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="courses.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="material",
            field=models.OneToOneField(
                help_text="Материал",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test",
                to="courses.material",
                verbose_name="Материал",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                help_text="Тест",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="courses.test",
                verbose_name="Тест",
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="test",
            field=models.ForeignKey(
                help_text="Тест",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="courses.test",
                verbose_name="Тест",
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="user",
            field=models.ForeignKey(
                help_text="Студент",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_results",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Студент",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="answer",
            field=models.ForeignKey(
                help_text="Ответ",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.answer",
                verbose_name="Ответ",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="question",
            field=models.ForeignKey(
                help_text="Вопрос",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="test_result",
            field=models.ForeignKey(
                help_text="Результат тестирования",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="courses.testresult",
                verbose_name="Результат тестирования",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="material",
            unique_together={("course", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="testresult",
            unique_together={("user", "test")},
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together={("test_result", "question")},
        ),
    ]
