# Generated by Django 5.2 on 2025-05-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="is_passed",
            field=models.BooleanField(
                default=False,
                help_text="Статус прохождения",
                verbose_name="Статус прохождения",
            ),
        ),
    ]
