# Generated by Django 5.2 on 2025-05-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_testresult_is_passed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="material",
            field=models.ForeignKey(
                help_text="Материал",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test",
                to="courses.material",
                verbose_name="Материал",
            ),
        ),
    ]
