# Generated by Django 5.2 on 2025-05-05 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_test_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="material",
            field=models.ForeignKey(
                help_text="Материал",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="courses.material",
                verbose_name="Материал",
            ),
        ),
    ]
